- name: "Install aptitude using apt"
  apt:
    name: aptitude
    state: latest
    update_cache: yes
    force_apt_get: yes

- name: "Installing docker apt dependencies"
  apt:
    name: ['apt-transport-https', 'ca-certificates', 'curl', 'gnupg-agent', 'software-properties-common']
    state: latest
    update_cache: true
  become: yes

- name: "Get apt key"
  apt_key:
    url: "https://download.docker.com/linux/ubuntu/gpg"

- name: "Add apt repository"
  apt_repository:
    repo: "deb https://download.docker.com/linux/ubuntu bionic stable"
    state: present

- name: "Install docker"
  apt:
    name: ['docker-ce', 'docker-ce-cli', 'containerd.io']
    state: latest
    update_cache: true

- name: "Install docker-compose"
  get_url:
    url: https://github.com/docker/compose/releases/download/1.25.1-rc1/docker-compose-Linux-x86_64
    dest: /usr/local/bin/docker-compose
    mode: "u+x,g+x"