version: '3.7'
services:
  backend:
    build: ./backend
    container_name: backend
    image: scottynic112/backend:latest
    ports:
    - target: 5001
      published: 5001
      protocol: tcp
    
  frontend:
    build: ./frontend
    container_name: frontend
    image: scottynic112/frontend:latest
    ports:
    - target: 5000
      published: 5000
      protocol: tcp
  nginx:
    build: ./nginx
    ports:
    - target: 80
      published: 80
      protocol: tcp
    volumes:
    - type: bind
      source: ./nginx/nginx.conf
      target: /etc/nginx/nginx.conf
