version: "3.7"
services:
  frontend:
  build: ./frontend
    image: scottynic112/front_end:latest
    container_name: frontend
    ports:
    - target: 5000
    published: 5000
    protocol: tcp
  backend:
    build: ./backend
    image: scottynic112/back_end:latest
    container_name: backend
    ports:
    - target: 5001
    published: 5001
    protocol: tcp