apiVersion: apps/v1
kind: Deployment
metadata:
  name: backend
  namespace: flaskapp
  labels:
    app: backend
spec:
  replicas: 3
  selector:
    matchLabels:
      app: backend
  template:
    metadata:
      labels:
        app: backend
    spec:
      containers:
      - name: backend
        image: scottynic112/backend:latest
        ports:
        - containerPort: 5001
        env:
        - name: DATABASE_URI
          valueFrom:
            secretKeyRef:
              name: credentials
              key: DATABASE_URI
        - name: TEST_DATABASE_URI
          valueFrom:
            secretKeyRef:
              name: credentials
              key: TEST_DATABASE_URI
        - name: secret_key
          valueFrom:
            secretKeyRef:
              name: credentials
              key: secret_key