apiVersion: apps/v1
kind: Deployment
metadata: 
  name: frontend
  namespace: flaskapp
  labels: 
    app: flask

spec: 
  replicas: 3
  selector: 
    matchLabels:
      app: flask
  template: 
    metadata: 
      labels:
        app: flask
    spec: 
      containers:
      - name: frontend
        image: scottynic112/frontend:latest
        ports: 
        - containerPort: 5000
        env:
        - name: DATABASE_URI
          valueFrom:
            secretKeyRef:
              name: credentials
              key: DATABASE_URI
        - name: TEST_DATABASE_URI
          valueFrom:
            secretKeyRef:
              name: credentials
              key: TEST_DATABASE_URI
        - name: secret_key
          valueFrom:
            secretKeyRef:
              name: credentials
              key: secret_key