apiVersion: apps/v1
kind: Deployment
metadata: 
  name: flaskapp
  namespace: flaskapp
  labels: 
    app: flask

spec: 
  replicas: 3
  selector: 
    matchLabels:
      app: flask
  template: 
    metadata: 
      labels:
        app: flask
    spec: 
      containers:
      - name: flaskapp
        image: scottynic112/front-end:latest
        ports: 
        - containerPort: 5000