apiVersion: v1
kind: Service
metadata:
  name: flaskapp
  namespace: flaskapp
  labels: 
    app: flask

spec:
  selector: 
    app: flask
  ports:
  - protocol: TCP
    port: 5000
    targetPort: 5000
  type: ClusterIP