apiVersion: v1
kind: ConfigMap
metadata: 
  name: nginxconfig
  namespace: flaskapp
data: 
  default.conf: 
    server {
        listen 80;
        location / {
            proxy_pass http://flask-app:5000;
        }
    }